name: Zsolt Bátorfi
favicon: null
layout_spectrum: 0.24449
typography_spectrum: 0.49944
title: the Journey of my professional existence
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdf8f5'
    - '#1c323f'
    - '#9d8579'
    - '#d9b59f'
    - '#a43410'
  brandStrength: 0.5268701200839132
  lightness: 0.3998912707902491
  saturation: 0.10909989173524082
  rhythmicContrast: 0.75
purpose: []
