name: Zsolt Bátorfi
favicon: null
layout_spectrum: 0.48764
typography_spectrum: 0.49944
title: the Journey of my professional existence
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5268701200839132
  lightness: 0.3998912707902491
  saturation: 0.10909989173524082
  rhythmicContrast: 0.75
purpose: []
